// Generated by scripts/build-browser-traits.mjs
export const TRAIT_VALUE_DICTIONARY=[];
export const TRAIT_ROWS=[[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[]];
