import {fileURLToPath} from 'node:url';
import test from 'node:test';
import assert from 'node:assert/strict';
import {build} from 'esbuild';
import {Miniflare} from 'miniflare';
test('shared edits persist, broadcast, reject stale writes and validate imports',async t=>{
 const bundled=await build({entryPoints:[fileURLToPath(new URL('../src/minote.js',import.meta.url))],bundle:true,write:false,format:'esm',platform:'browser'});
 const mf=new Miniflare({modules:true,script:bundled.outputFiles[0].text,compatibilityDate:'2026-08-04',durableObjects:{CURATOR:{className:'Curator',useSQLite:true}},unsafeStickyBlobs:true});
 t.after(()=>mf.dispose());
 const call=(path,body,origin='https://cards.art')=>mf.dispatchFetch('http://local'+path,{method:body?'POST':'GET',headers:{Origin:origin,'Content-Type':'application/json'},...(body?{body:JSON.stringify(body)}:{})});
 assert.equal((await call('/api/edits',null,'https://bad.example')).status,403);
 const suits=await (await call('/api/suits')).json();assert.equal(suits.spacing,suits.spacingY);
 const styled=await (await call('/api/suits',{...suits,stroke:true,spacingX:80,spacingY:120})).json();
 const oldClient=await (await call('/api/suits',{visible:true,side:'left',orientation:'vertical',size:110,spacing:90,seed:1729,revision:styled.revision})).json();
 assert.equal(oldClient.stroke,true);assert.equal(oldClient.spacingX,90);assert.equal(oldClient.spacingY,90);
 const compatible=await (await call('/api/suits')).json();assert.equal(compatible.spacing,90);
 const iconResult=await call('/api/icon',{id:95,icon:{type:'tear',color:'emerald'}});assert.equal(iconResult.status,200);
 const iconMeta=await iconResult.json();assert.equal(iconMeta.icons[95].type,'tear');assert.ok(iconMeta.cards[95].includes('tear'));assert.ok(iconMeta.cards[95].includes('emerald icon'));
 const nextIcon=await (await call('/api/icon',{id:95,icon:{type:'bell'}})).json();assert.equal(nextIcon.icons[95].color,'emerald');assert.ok(!nextIcon.cards[95].includes('tear'));assert.ok(nextIcon.cards[95].includes('bell icon'));
 assert.equal((await call('/api/icon',{id:95,icon:{type:'invalid'}})).status,400);
 const beforeBatch=await (await call('/api/metadata')).json(),suitBatch=await (await call('/api/suits')).json();
 const batch={revision:beforeBatch.revision,suitsRevision:suitBatch.revision,colors:{95:'marigold',96:'emerald'}};
 assert.equal((await call('/api/icon-colors',{...batch,revision:-1})).status,409);
 assert.equal((await call('/api/icon-colors',{...batch,colors:{95:'bad'}})).status,400);
 assert.equal((await call('/api/icon-colors',batch)).status,200);
 const afterBatch=await (await call('/api/metadata')).json();assert.equal(afterBatch.icons[95].type,'bell');assert.equal(afterBatch.icons[95].color,'marigold');assert.ok(afterBatch.cards[95].includes('marigold icon'));assert.ok(!afterBatch.cards[95].includes('emerald icon'));
 await call('/api/tags',{id:95,tag:'emerald',selected:true});
 const hidden=await (await call('/api/icon',{id:95,icon:{hidden:true}})).json();
 assert.equal(hidden.icons[95].hidden,true);assert.ok(hidden.cards[95].includes('special'));assert.ok(hidden.cards[95].includes('so special'));assert.ok(hidden.cards[95].includes('emerald'));assert.ok(!hidden.cards[95].includes('marigold icon'));assert.ok(!hidden.cards[95].includes('bell icon'));
 const shown=await (await call('/api/icon',{id:95,icon:{hidden:false}})).json();assert.ok(shown.cards[95].includes('bell icon'));assert.ok(shown.cards[95].includes('marigold icon'));assert.ok(shown.cards[95].includes('emerald'));assert.ok(!shown.cards[95].includes('so special'));

 await call('/api/tags',{id:95,tag:'bell',selected:true});
 const changed=await (await call('/api/icon',{id:95,icon:{type:'heart'}})).json();
 assert.ok(changed.cards[95].includes('bell'));assert.ok(changed.cards[95].includes('heart icon'));assert.ok(!changed.cards[95].includes('bell icon'));
 const removedSubject=await (await call('/api/tags',{id:95,tag:'bell',selected:false})).json();assert.ok(!removedSubject.cards[95].includes('bell'));assert.equal(removedSubject.icons[95].type,'heart');
 const seed=await (await call('/api/edits')).json();const id=1;
 const connection=await mf.dispatchFetch('http://local/connect',{headers:{Origin:'https://cards.art',Upgrade:'websocket'}});
 const ws=connection.webSocket;ws.accept();t.after(()=>ws.close());
 const notification=new Promise(resolve=>ws.addEventListener('message',e=>resolve(e.data),{once:true}));
 const data={id,...seed[id],nameX:-2400,nameY:3200,_revision:seed[id]?._revision||0};
 const a=await call('/api/save',data);assert.equal(a.status,200);const saved=await a.json();
 assert.equal(await notification,'changed');
 const read=await (await call('/api/edits')).json();assert.equal(read[id].nameX,-2400);assert.equal(read[id].nameY,3200);
 assert.equal((await call('/api/save',data)).status,409);
 assert.equal((await call('/api/save',{...data,_revision:saved._revision,nameX:'bad'})).status,400);
 assert.equal((await call('/api/import',{version:1,edits:{[id]:{zoom:1.3}},revisions:{[id]:0}})).status,409);
 assert.equal((await call('/api/import',{version:1,edits:{[id]:{zoom:1.3}},revisions:{[id]:saved._revision}})).status,200);
 assert.equal((await (await call('/api/edits')).json())[id].zoom,1.3);

 const metadata=await (await call('/api/metadata')).json();
 const used=new Set(Object.values(metadata.cards).flat());
 assert.deepEqual(metadata.tags,[...used].sort());
 assert.equal((await (await call('/api/metadata')).json()).revision,metadata.revision);
 assert.ok(metadata.tags.includes('pokemon'));assert.ok(metadata.cards[id].includes('angel'));
 for(const tag of ['favorite','remilio','invader']){
  assert.ok(!metadata.tags.includes(tag));
  assert.equal((await call('/api/tags',{id,tag,selected:true})).status,200);
 }
 const restored=await (await call('/api/metadata')).json();
 for(const tag of ['favorite','remilio','invader']){assert.ok(restored.tags.includes(tag));assert.ok(restored.cards[id].includes(tag));}
 assert.deepEqual(restored.icons,metadata.icons);assert.deepEqual(restored.iconOverrides,metadata.iconOverrides);
 assert.deepEqual(restored.cards[2],metadata.cards[2]);
 assert.equal((await call('/api/tags',{id,tag:'favorite',selected:false})).status,200);
 const removedAgain=await (await call('/api/metadata')).json();assert.ok(!removedAgain.cards[id].includes('favorite'));assert.ok(!removedAgain.tags.includes('favorite'));
 const restoredAgain=await (await call('/api/tags',{id,tag:'favorite',selected:true})).json();
 assert.ok(restoredAgain.tags.includes('favorite'));assert.ok(restoredAgain.cards[id].includes('favorite'));
 const add=await call('/api/tags',{id,tag:'  New Tag  ',selected:true});assert.equal(add.status,200);
 const tagged=await add.json();assert.ok(tagged.tags.includes('new tag'));assert.ok(tagged.cards[id].includes('new tag'));
 assert.equal((await call('/api/tags',{id:2,tag:'new tag',selected:true})).status,200);
 const stillUsed=await (await call('/api/tags',{id,tag:'new tag',selected:false})).json();assert.ok(stillUsed.tags.includes('new tag'));
 const unused=await (await call('/api/tags',{id:2,tag:'new tag',selected:false})).json();assert.ok(!unused.tags.includes('new tag'));
 const cleanupRevision=unused.revision;
 const cleanedRead=await (await call('/api/metadata')).json();assert.ok(!cleanedRead.tags.includes('new tag'));assert.equal(cleanedRead.revision,cleanupRevision);
 assert.equal((await call('/api/tags',{id:2,tag:'new tag',selected:true})).status,200);
 await Promise.all([call('/api/tags',{id,tag:'concurrent one',selected:true}),call('/api/tags',{id,tag:'concurrent two',selected:true})]);
 const merged=await (await call('/api/metadata')).json();
 assert.ok(merged.cards[id].includes('concurrent one'));assert.ok(merged.cards[id].includes('concurrent two'));
 assert.equal((await call('/api/tags',{id,tag:'angel',selected:false})).status,200);
 const removed=await (await call('/api/metadata')).json();assert.ok(!removed.cards[id].includes('angel'));assert.ok(removed.tags.includes('angel'));
 assert.equal((await call('/api/tags',{id:999999,tag:'invalid',selected:true})).status,400);
 assert.equal((await call('/api/tags',{id,tag:'<script>',selected:true})).status,400);
 assert.equal((await call('/api/tags',{id,tag:'valid',selected:'yes'})).status,400);
 const reread=await (await call('/api/edits')).json();assert.equal(reread[id].zoom,1.3);
 assert.ok((await (await call('/api/metadata')).json()).cards[2].includes('new tag'));
});
