import {fileURLToPath} from 'node:url';
import test from 'node:test';
import assert from 'node:assert/strict';
import {build} from 'esbuild';
import {Miniflare} from 'miniflare';
test('shared edits persist, broadcast, reject stale writes and validate imports',async t=>{
 const bundled=await build({entryPoints:[fileURLToPath(new URL('../src/minote.js',import.meta.url))],bundle:true,write:false,format:'esm',platform:'browser'});
 const mf=new Miniflare({modules:true,script:bundled.outputFiles[0].text,compatibilityDate:'2026-08-04',durableObjects:{CURATOR:{className:'Curator',useSQLite:true}},unsafeStickyBlobs:true});
 t.after(()=>mf.dispose());
 const call=(path,body,origin='https://cards.art')=>mf.dispatchFetch('http://local'+path,{method:body?'POST':'GET',headers:{Origin:origin,'Content-Type':'application/json'},...(body?{body:JSON.stringify(body)}:{})});
 assert.equal((await call('/api/edits',null,'https://bad.example')).status,403);
 const seed=await (await call('/api/edits')).json();const id=1;
 const connection=await mf.dispatchFetch('http://local/connect',{headers:{Origin:'https://cards.art',Upgrade:'websocket'}});
 const ws=connection.webSocket;ws.accept();t.after(()=>ws.close());
 const notification=new Promise(resolve=>ws.addEventListener('message',e=>resolve(e.data),{once:true}));
 const data={id,...seed[id],nameX:-2400,nameY:3200,_revision:seed[id]?._revision||0};
 const a=await call('/api/save',data);assert.equal(a.status,200);const saved=await a.json();
 assert.equal(await notification,'changed');
 const read=await (await call('/api/edits')).json();assert.equal(read[id].nameX,-2400);assert.equal(read[id].nameY,3200);
 assert.equal((await call('/api/save',data)).status,409);
 assert.equal((await call('/api/save',{...data,_revision:saved._revision,nameX:'bad'})).status,400);
 assert.equal((await call('/api/import',{version:1,edits:{[id]:{zoom:1.3}},revisions:{[id]:0}})).status,409);
 assert.equal((await call('/api/import',{version:1,edits:{[id]:{zoom:1.3}},revisions:{[id]:saved._revision}})).status,200);
 assert.equal((await (await call('/api/edits')).json())[id].zoom,1.3);
});
