// PNGs are already compressed; ZIP STORE avoids a second costly compression pass.
export function zipFiles(files){
 const chunks=[],directory=[];let offset=0;
 const crc=bytes=>{let c=0xffffffff;for(const b of bytes){c^=b;for(let i=0;i<8;i++)c=(c>>>1)^((c&1)?0xedb88320:0);}return (c^0xffffffff)>>>0;};
 for(const {name,data} of files){const filename=new TextEncoder().encode(name),sum=crc(data),header=new Uint8Array(30+filename.length),h=new DataView(header.buffer);h.setUint32(0,0x04034b50,true);h.setUint16(4,20,true);h.setUint32(14,sum,true);h.setUint32(18,data.length,true);h.setUint32(22,data.length,true);h.setUint16(26,filename.length,true);header.set(filename,30);chunks.push(header,data);
 const entry=new Uint8Array(46+filename.length),d=new DataView(entry.buffer);d.setUint32(0,0x02014b50,true);d.setUint16(4,20,true);d.setUint16(6,20,true);d.setUint32(16,sum,true);d.setUint32(20,data.length,true);d.setUint32(24,data.length,true);d.setUint16(28,filename.length,true);d.setUint32(42,offset,true);entry.set(filename,46);directory.push(entry);offset+=header.length+data.length;}
 const end=new Uint8Array(22),e=new DataView(end.buffer);e.setUint32(0,0x06054b50,true);e.setUint16(8,files.length,true);e.setUint16(10,files.length,true);e.setUint32(12,directory.reduce((sum,v)=>sum+v.length,0),true);e.setUint32(16,offset,true);return new Blob([...chunks,...directory,end],{type:'application/zip'});
}
const options=[['full','Full card art'],['art','Original art (with current crop)'],['name-box','Name box'],['body-box','Body box'],['boxes','Both boxes together'],['name','Name'],['body-text','Body text'],['texts','Both texts together'],['icons','Icons'],['overlays','Everything except original art']];
export function createExportOptions({render,download}){
 const dialog=document.createElement('dialog');dialog.id='exportOptions';dialog.setAttribute('aria-labelledby','exportOptionsTitle');
 dialog.innerHTML='<h2 id="exportOptionsTitle">Download card layers</h2><p>Each PNG is 2000 × 2800 px, using the current edits and transparency where applicable.</p><div class="export-choices"></div><p class="export-note">Body text is extracted from the supplied printed artwork. Hidden body boxes and icons export as transparent layers.</p><progress max="100" value="0" hidden></progress><p class="export-status" role="status" aria-live="polite"></p><div class="export-actions"><button type="button" class="export-cancel">Cancel</button><button type="button" class="primary export-confirm">Confirm download</button></div>';
 const choices=dialog.querySelector('.export-choices');for(const [key,label]of options){const row=document.createElement('label'),input=document.createElement('input');input.type='checkbox';input.value=key;input.checked=key==='full';row.append(input,document.createTextNode(label));choices.append(row);}
 document.body.append(dialog);let current,busy=false;const confirm=dialog.querySelector('.export-confirm'),cancel=dialog.querySelector('.export-cancel'),progress=dialog.querySelector('progress'),status=dialog.querySelector('.export-status');
 choices.onchange=()=>confirm.disabled=!choices.querySelector('input:checked');cancel.onclick=()=>dialog.close();dialog.addEventListener('cancel',e=>{if(busy)e.preventDefault();});dialog.addEventListener('click',e=>{if(e.target===dialog&&!busy){const r=dialog.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)dialog.close();}});
 confirm.onclick=async()=>{if(busy)return;busy=true;const selected=[...choices.querySelectorAll('input:checked')].map(i=>i.value);confirm.disabled=cancel.disabled=true;choices.querySelectorAll('input').forEach(i=>i.disabled=true);progress.hidden=false;progress.value=0;dialog.setAttribute('aria-busy','true');
 try{const files=[];for(let i=0;i<selected.length;i++){const key=selected[i];status.textContent=`Rendering ${options.find(o=>o[0]===key)[1]} (${i+1}/${selected.length})…`;await new Promise(requestAnimationFrame);const blob=await render(current.item,current.edits,key);files.push({name:`mi-note-${String(current.item.id).padStart(4,'0')}-${key}.png`,data:new Uint8Array(await blob.arrayBuffer())});progress.value=(i+1)/(selected.length+1)*100;}
 status.textContent='Packaging ZIP…';await new Promise(requestAnimationFrame);download(zipFiles(files),`mi-note-${String(current.item.id).padStart(4,'0')}-layers.zip`);progress.value=100;status.textContent=`Downloaded ${files.length} PNG${files.length===1?'':'s'} in one ZIP.`;cancel.textContent='Close';
 }catch(e){status.textContent='Download failed: '+e.message;}finally{busy=false;confirm.disabled=false;cancel.disabled=false;choices.querySelectorAll('input').forEach(i=>i.disabled=false);dialog.removeAttribute('aria-busy');}};
 return (item,edits)=>{current={item,edits:{...edits}};progress.hidden=true;progress.value=0;status.textContent='';cancel.textContent='Cancel';dialog.showModal();};
}
